from feature.base import *
from feature.txt import *
from feature.ext_rand import *
from feature.absolute_kid import *
from feature.end import *
from feature.ext_img import *
from feature.gif import *
from feature.greet import *
from feature.header import *
from feature.movie import *
from feature.music import *
from feature.one import *
from feature.poem import *
from feature.weather import *
from feature.zhihu_daily import *
from feature.zhihu_story import *
